runtime: python
pythonVersion: 3.9

services:
  - type: web
    name: mood-detection-webapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    plan: free
